import { Prop, Schema, SchemaFactory } from '@nestjs/mongoose';
import { Document, Types } from 'mongoose';
import { IBusiness } from '../../../../domain/model/business/business.interface';


export type BusinessDocument = Business & Document;

@Schema()
export class Business implements IBusiness{

    //@Prop({type: Types.ObjectId})
    //_id: holds an ObjectId autogenerated. Iimplicitly has "index: true".

    @Prop()
    key: string;
  
    @Prop({ type: Types.Map })
    meta: any;
}

export const BusinessSchema = SchemaFactory.createForClass(Business);

